spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cdek:
  base-url: https://api.edu.cdek.ru/v2
  client-id: wqGwiQx0gg8mLtiEKsUinjVSICCjtTEP
  client-secret: RmAmgvSgSl1yirlz9QupbzOJVqhCxcP5

