@host = http://localhost:8080
@orderId = 1
@productId = 1
@orderItemId = 1

###
POST {{host}}/api/order-items
Content-Type: application/json

{
  "productId": {{productId}},
  "orderId": {{orderId}},
  "quantity": 2
}
###

GET {{host}}/api/order-items/{{orderItemId}}
Accept: application/json
