@host = http://localhost:8080
@userId = 1
@orderId = 1

###
POST {{host}}/api/orders/{{userId}}/user
Accept: application/json

###
GET {{host}}/api/orders/{{orderId}}
Accept: application/json

###
GET {{host}}/api/orders?page=0&size=10
Accept: application/json

