@host = http://localhost:8080
@orderId = 1
@shipmentId = 1

###
POST {{host}}/api/shipments
Content-Type: application/json

{
  "orderId": {{orderId}},
  "trackingNumber": "TRK-001",
  "carrier": "CDEK",
  "shippingAddress": "Bishkek, Chui 123"
}

###
GET {{host}}/api/shipments/{{shipmentId}}
Accept: application/json
